language: ruby
rvm:
  - 2.1.1

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database angry_kitty_test;' -U postgres

test:
  adapter: postgresql
  database: angry_kitty_test
  username: postgres

script:
  - cucumber
  - rspec