language: ruby
rvm:
  - 2.1.1

addons:
  postgresql: "9.3"

before_script:
  - psql -c 'create database angry_kitty_test;' -U postgres
  - cp config/secrets.yml.travis config/secrets.yml

test:
  adapter: postgresql
  database: angry_kitty_test
  username: postgres

script: bundle exec rake cucumber